cmake_minimum_required(VERSION 4.1)
project(InterstellarOutpost_dx12)

set(CMAKE_CXX_STANDARD 14)

include_directories(GameLogic)
include_directories(InterstellarOutpost)
include_directories(NeuronClient)
include_directories(NeuronCore)
include_directories(NeuronCore/unrar)

add_executable(InterstellarOutpost_dx12
        GameLogic/AchievementButton.h
        GameLogic/AdvancedOptionsModeButton.h
        GameLogic/ai.cpp
        GameLogic/ai.h
        GameLogic/aiobjective.cpp
        GameLogic/aiobjective.h
        GameLogic/airstrike.cpp
        GameLogic/airstrike.h
        GameLogic/anthill.cpp
        GameLogic/anthill.h
        GameLogic/AnyLevelSelectButton.h
        GameLogic/ApplyNameButton.h
        GameLogic/armour.cpp
        GameLogic/armour.h
        GameLogic/armyant.cpp
        GameLogic/armyant.h
        GameLogic/blueprintstore.cpp
        GameLogic/blueprintstore.h
        GameLogic/bridge.cpp
        GameLogic/bridge.h
        GameLogic/building.cpp
        GameLogic/building.h
        GameLogic/BuyNowInfoButton.h
        GameLogic/BuyNowModeButton.h
        GameLogic/CampaignButton.h
        GameLogic/carryablebuilding.cpp
        GameLogic/carryablebuilding.h
        GameLogic/cave.cpp
        GameLogic/cave.h
        GameLogic/centipede.cpp
        GameLogic/centipede.h
        GameLogic/chatinput_window.cpp
        GameLogic/chatinput_window.h
        GameLogic/cheat_window.cpp
        GameLogic/cheat_window.h
        GameLogic/checkbox.cpp
        GameLogic/checkbox.h
        GameLogic/chess.cpp
        GameLogic/chess.h
        GameLogic/clonelab.cpp
        GameLogic/clonelab.h
        GameLogic/ConnectButton.h
        GameLogic/constructionyard.cpp
        GameLogic/constructionyard.h
        GameLogic/controllerunplugged_window.cpp
        GameLogic/controllerunplugged_window.h
        GameLogic/controlstation.cpp
        GameLogic/controlstation.h
        GameLogic/controltower.cpp
        GameLogic/controltower.h
        GameLogic/crate.cpp
        GameLogic/crate.h
        GameLogic/credits_button.h
        GameLogic/CSpectatorButton.h
        GameLogic/darwinia_window.cpp
        GameLogic/darwinia_window.h
        GameLogic/DarwiniaModeButton.h
        GameLogic/darwinian.cpp
        GameLogic/darwinian.h
        GameLogic/DarwiniaPlusMPButton.h
        GameLogic/DarwiniaPlusSPButton.h
        GameLogic/debugmenu.cpp
        GameLogic/debugmenu.h
        GameLogic/drop_down_menu.cpp
        GameLogic/drop_down_menu.h
        GameLogic/dropship.cpp
        GameLogic/dropship.h
        GameLogic/dustball.cpp
        GameLogic/dustball.h
        GameLogic/egg.cpp
        GameLogic/egg.h
        GameLogic/engineer.cpp
        GameLogic/engineer.h
        GameLogic/entity.cpp
        GameLogic/entity.h
        GameLogic/entity_leg.cpp
        GameLogic/entity_leg.h
        GameLogic/ErrorDialog.cpp
        GameLogic/ErrorDialog.h
        GameLogic/eruptionmarker.cpp
        GameLogic/eruptionmarker.h
        GameLogic/factory.cpp
        GameLogic/factory.h
        GameLogic/FancyColourButton.h
        GameLogic/feedingtube.cpp
        GameLogic/feedingtube.h
        GameLogic/filedialog.cpp
        GameLogic/filedialog.h
        GameLogic/FiltersPageButton.h
        GameLogic/FinishMultiwiniaButton.h
        GameLogic/flag.cpp
        GameLogic/flag.h
        GameLogic/GameMenuOptionsButton.h
        GameLogic/GameMenuWindow.cpp
        GameLogic/GameMenuWindow.h
        GameLogic/GamerTagButton.h
        GameLogic/GameTypeAnyButton.h
        GameLogic/GameTypeButton.h
        GameLogic/GameTypeImageButton.h
        GameLogic/GameTypeInfoButton.h
        GameLogic/generator.cpp
        GameLogic/generator.h
        GameLogic/generichub.cpp
        GameLogic/generichub.h
        GameLogic/goddish.cpp
        GameLogic/goddish.h
        GameLogic/gunturret.cpp
        GameLogic/gunturret.h
        GameLogic/harvester.cpp
        GameLogic/harvester.h
        GameLogic/helpandoptions_windows.cpp
        GameLogic/helpandoptions_windows.h
        GameLogic/HelpImageButton.h
        GameLogic/HelpSelectButton.h
        GameLogic/ImageButton.cpp
        GameLogic/ImageButton.h
        GameLogic/incubator.cpp
        GameLogic/incubator.h
        GameLogic/input_field.cpp
        GameLogic/input_field.h
        GameLogic/insertion_squad.cpp
        GameLogic/insertion_squad.h
        GameLogic/JoinGameButton.h
        GameLogic/jumppad.cpp
        GameLogic/jumppad.h
        GameLogic/KickPlayerButton.h
        GameLogic/lander.cpp
        GameLogic/lander.h
        GameLogic/laserfence.cpp
        GameLogic/laserfence.h
        GameLogic/lasertrooper.cpp
        GameLogic/lasertrooper.h
        GameLogic/LevelSelectButton.h
        GameLogic/LevelSelectButtonBase.h
        GameLogic/library.cpp
        GameLogic/library.h
        GameLogic/lightning.cpp
        GameLogic/lightning.h
        GameLogic/mainmenus.cpp
        GameLogic/mainmenus.h
        GameLogic/MapData.cpp
        GameLogic/MapData.h
        GameLogic/mapDetailsButton.h
        GameLogic/MapImageButton.h
        GameLogic/MapInfoButton.h
        GameLogic/MapListTitlesButton.h
        GameLogic/MapSelectModeButton.h
        GameLogic/message_dialog.cpp
        GameLogic/message_dialog.h
        GameLogic/meteor.cpp
        GameLogic/meteor.h
        GameLogic/mine.cpp
        GameLogic/mine.h
        GameLogic/motdButton.h
        GameLogic/multiwinia_filedialog.cpp
        GameLogic/multiwinia_filedialog.h
        GameLogic/multiwinia_window.cpp
        GameLogic/multiwinia_window.h
        GameLogic/MultiwiniaModeButton.h
        GameLogic/MultiwiniaVersusCpuButton.h
        GameLogic/multiwiniazone.cpp
        GameLogic/multiwiniazone.h
        GameLogic/network_window.cpp
        GameLogic/network_window.h
        GameLogic/NewOrJoinButton.h
        GameLogic/NewServerButton.h
        GameLogic/NextHelpButton.h
        GameLogic/nuke.cpp
        GameLogic/nuke.h
        GameLogic/officer.cpp
        GameLogic/officer.h
        GameLogic/OptionDetailsButton.h
        GameLogic/PasteKeyButton.h
        GameLogic/pch.cpp
        GameLogic/pch.h
        GameLogic/PlayGameButton.h
        GameLogic/portal.cpp
        GameLogic/portal.h
        GameLogic/powerstation.cpp
        GameLogic/powerstation.h
        GameLogic/prefs_graphics_window.cpp
        GameLogic/prefs_graphics_window.h
        GameLogic/prefs_keybindings_window.cpp
        GameLogic/prefs_keybindings_window.h
        GameLogic/prefs_other_window.cpp
        GameLogic/prefs_other_window.h
        GameLogic/prefs_screen_window.cpp
        GameLogic/prefs_screen_window.h
        GameLogic/prefs_sound_window.cpp
        GameLogic/prefs_sound_window.h
        GameLogic/PrevHelpButton.h
        GameLogic/profilewindow.cpp
        GameLogic/profilewindow.h
        GameLogic/PrologueButton.h
        GameLogic/pulsebomb.cpp
        GameLogic/pulsebomb.h
        GameLogic/QuickMatchButton.h
        GameLogic/QuickStartButton.h
        GameLogic/QuitButton.h
        GameLogic/radardish.cpp
        GameLogic/radardish.h
        GameLogic/randomiser.cpp
        GameLogic/randomiser.h
        GameLogic/reallyquit_window.cpp
        GameLogic/reallyquit_window.h
        GameLogic/RequestAIButton.h
        GameLogic/researchitem.cpp
        GameLogic/researchitem.h
        GameLogic/ResearchModeButton.h
        GameLogic/restrictionzone.cpp
        GameLogic/restrictionzone.h
        GameLogic/rocket.cpp
        GameLogic/rocket.h
        GameLogic/safearea.cpp
        GameLogic/safearea.h
        GameLogic/scripttrigger.cpp
        GameLogic/scripttrigger.h
        GameLogic/scrollbar.cpp
        GameLogic/scrollbar.h
        GameLogic/ScrollingTextButton.h
        GameLogic/ServerTitleInfoButton.h
        GameLogic/shaman.cpp
        GameLogic/shaman.h
        GameLogic/smokemarker.cpp
        GameLogic/smokemarker.h
        GameLogic/snow.cpp
        GameLogic/snow.h
        GameLogic/souldestroyer.cpp
        GameLogic/souldestroyer.h
        GameLogic/soundsliderbutton.h
        GameLogic/spaceship.cpp
        GameLogic/spaceship.h
        GameLogic/spam.cpp
        GameLogic/spam.h
        GameLogic/spawnpoint.cpp
        GameLogic/spawnpoint.h
        GameLogic/spider.cpp
        GameLogic/spider.h
        GameLogic/spirit.cpp
        GameLogic/spirit.h
        GameLogic/spiritreceiver.cpp
        GameLogic/spiritreceiver.h
        GameLogic/spiritstore.cpp
        GameLogic/spiritstore.h
        GameLogic/sporegenerator.cpp
        GameLogic/sporegenerator.h
        GameLogic/staticshape.cpp
        GameLogic/staticshape.h
        GameLogic/statue.cpp
        GameLogic/statue.h
        GameLogic/switch.cpp
        GameLogic/switch.h
        GameLogic/tank.cpp
        GameLogic/tank.h
        GameLogic/teleport.cpp
        GameLogic/teleport.h
        GameLogic/tentacle.cpp
        GameLogic/tentacle.h
        GameLogic/TestBedButtons.h
        GameLogic/tree.cpp
        GameLogic/tree.h
        GameLogic/triffid.cpp
        GameLogic/triffid.h
        GameLogic/tripod.cpp
        GameLogic/tripod.h
        GameLogic/trunkport.cpp
        GameLogic/trunkport.h
        GameLogic/UnlockFullGameButton.h
        GameLogic/update_page_buttons.h
        GameLogic/updateavailable_window.cpp
        GameLogic/updateavailable_window.h
        GameLogic/upgrade_port.cpp
        GameLogic/upgrade_port.h
        GameLogic/userprofile_window.cpp
        GameLogic/userprofile_window.h
        GameLogic/virii.cpp
        GameLogic/virii.h
        GameLogic/WaitingButton.h
        GameLogic/wall.cpp
        GameLogic/wall.h
        GameLogic/wallbuster.cpp
        GameLogic/wallbuster.h
        GameLogic/weapons.cpp
        GameLogic/weapons.h
        GameLogic/worldobject.cpp
        GameLogic/worldobject.h
        InterstellarOutpost/3d_sierpinski_gasket.cpp
        InterstellarOutpost/3d_sierpinski_gasket.h
        InterstellarOutpost/achievement_tracker.cpp
        InterstellarOutpost/achievement_tracker.h
        InterstellarOutpost/animatedpanel.cpp
        InterstellarOutpost/animatedpanel.h
        InterstellarOutpost/animatedpanel_renderer.cpp
        InterstellarOutpost/animatedpanel_renderer.h
        InterstellarOutpost/app.cpp
        InterstellarOutpost/app.h
        InterstellarOutpost/attract.cpp
        InterstellarOutpost/attract.h
        InterstellarOutpost/camera.cpp
        InterstellarOutpost/camera.h
        InterstellarOutpost/clouds.cpp
        InterstellarOutpost/clouds.h
        InterstellarOutpost/deform.cpp
        InterstellarOutpost/deform.h
        InterstellarOutpost/entity_grid.cpp
        InterstellarOutpost/entity_grid.h
        InterstellarOutpost/entity_grid_cache.cpp
        InterstellarOutpost/entity_grid_cache.h
        InterstellarOutpost/explosion.cpp
        InterstellarOutpost/explosion.h
        InterstellarOutpost/game_menu.cpp
        InterstellarOutpost/game_menu.h
        InterstellarOutpost/gamecursor.cpp
        InterstellarOutpost/gamecursor.h
        InterstellarOutpost/gametimer.cpp
        InterstellarOutpost/gametimer.h
        InterstellarOutpost/global_internet.cpp
        InterstellarOutpost/global_internet.h
        InterstellarOutpost/global_world.cpp
        InterstellarOutpost/global_world.h
        InterstellarOutpost/globals.h
        InterstellarOutpost/landscape.cpp
        InterstellarOutpost/landscape.h
        InterstellarOutpost/landscape_renderer.cpp
        InterstellarOutpost/landscape_renderer.h
        InterstellarOutpost/level_file.cpp
        InterstellarOutpost/level_file.h
        InterstellarOutpost/loading_screen.cpp
        InterstellarOutpost/loading_screen.h
        InterstellarOutpost/location.cpp
        InterstellarOutpost/location.h
        InterstellarOutpost/location_input.cpp
        InterstellarOutpost/location_input.h
        InterstellarOutpost/main.cpp
        InterstellarOutpost/main.h
        InterstellarOutpost/mapcrc.h
        InterstellarOutpost/mapfile.cpp
        InterstellarOutpost/mapfile.h
        InterstellarOutpost/markersystem.cpp
        InterstellarOutpost/markersystem.h
        InterstellarOutpost/multiwinia.cpp
        InterstellarOutpost/multiwinia.h
        InterstellarOutpost/obstruction_grid.cpp
        InterstellarOutpost/obstruction_grid.h
        InterstellarOutpost/particle_system.cpp
        InterstellarOutpost/particle_system.h
        InterstellarOutpost/pch.cpp
        InterstellarOutpost/pch.h
        InterstellarOutpost/renderer.cpp
        InterstellarOutpost/renderer.h
        InterstellarOutpost/rocket_status_panel.cpp
        InterstellarOutpost/rocket_status_panel.h
        InterstellarOutpost/routing_system.cpp
        InterstellarOutpost/routing_system.h
        InterstellarOutpost/script.cpp
        InterstellarOutpost/script.h
        InterstellarOutpost/sepulveda_strings.cpp
        InterstellarOutpost/shaman_interface.cpp
        InterstellarOutpost/shaman_interface.h
        InterstellarOutpost/startsequence.cpp
        InterstellarOutpost/startsequence.h
        InterstellarOutpost/taskmanager.cpp
        InterstellarOutpost/taskmanager.h
        InterstellarOutpost/taskmanager_interface.cpp
        InterstellarOutpost/taskmanager_interface.h
        InterstellarOutpost/taskmanager_interface_icons.cpp
        InterstellarOutpost/taskmanager_interface_icons.h
        InterstellarOutpost/taskmanager_interface_multiwinia.cpp
        InterstellarOutpost/taskmanager_interface_multiwinia.h
        InterstellarOutpost/team.cpp
        InterstellarOutpost/team.h
        InterstellarOutpost/testharness.cpp
        InterstellarOutpost/testharness.h
        InterstellarOutpost/unit.cpp
        InterstellarOutpost/unit.h
        InterstellarOutpost/user_input.cpp
        InterstellarOutpost/user_input.h
        InterstellarOutpost/water.cpp
        InterstellarOutpost/water.h
        InterstellarOutpost/water_reflection.cpp
        InterstellarOutpost/water_reflection.h
        NeuronClient/bandwidth.cpp
        NeuronClient/bandwidth.h
        NeuronClient/bytestream.h
        NeuronClient/clienttoserver.cpp
        NeuronClient/clienttoserver.h
        NeuronClient/control_bindings.cpp
        NeuronClient/control_bindings.h
        NeuronClient/control_types.cpp
        NeuronClient/control_types.h
        NeuronClient/d3dx12.h
        NeuronClient/DirectXHelper.h
        NeuronClient/eclbutton.cpp
        NeuronClient/eclbutton.h
        NeuronClient/eclipse.cpp
        NeuronClient/eclipse.h
        NeuronClient/eclwindow.cpp
        NeuronClient/eclwindow.h
        NeuronClient/eventhandler.cpp
        NeuronClient/eventhandler.h
        NeuronClient/file_paths.cpp
        NeuronClient/file_paths.h
        NeuronClient/ftp_manager.cpp
        NeuronClient/ftp_manager.h
        NeuronClient/generic.cpp
        NeuronClient/generic.h
        NeuronClient/iframe.cpp
        NeuronClient/iframe.h
        NeuronClient/input.cpp
        NeuronClient/input.h
        NeuronClient/input_types.cpp
        NeuronClient/input_types.h
        NeuronClient/inputdriver.cpp
        NeuronClient/inputdriver.h
        NeuronClient/inputdriver_alias.cpp
        NeuronClient/inputdriver_alias.h
        NeuronClient/inputdriver_chord.cpp
        NeuronClient/inputdriver_chord.h
        NeuronClient/inputdriver_conjoin.cpp
        NeuronClient/inputdriver_conjoin.h
        NeuronClient/inputdriver_idle.cpp
        NeuronClient/inputdriver_idle.h
        NeuronClient/inputdriver_invert.cpp
        NeuronClient/inputdriver_invert.h
        NeuronClient/inputdriver_prefs.cpp
        NeuronClient/inputdriver_prefs.h
        NeuronClient/inputdriver_simple.cpp
        NeuronClient/inputdriver_simple.h
        NeuronClient/inputdriver_value.cpp
        NeuronClient/inputdriver_value.h
        NeuronClient/inputdriver_win32.cpp
        NeuronClient/inputdriver_win32.h
        NeuronClient/inputfilter.cpp
        NeuronClient/inputfilter.h
        NeuronClient/inputfilter_withdelta.cpp
        NeuronClient/inputfilter_withdelta.h
        NeuronClient/inputfiltermanager.cpp
        NeuronClient/inputfiltermanager.h
        NeuronClient/inputfilterspec.cpp
        NeuronClient/inputfilterspec.h
        NeuronClient/inputspec.cpp
        NeuronClient/inputspec.h
        NeuronClient/inputspeclist.h
        NeuronClient/InputTransform.cpp
        NeuronClient/InputTransform.h
        NeuronClient/keydefs.h
        NeuronClient/keynames.cpp
        NeuronClient/keynames.h
        NeuronClient/listener.cpp
        NeuronClient/listener.h
        NeuronClient/movement2d.cpp
        NeuronClient/movement2d.h
        NeuronClient/network_defines.h
        NeuronClient/network_defines_debug.h
        NeuronClient/network_quality.cpp
        NeuronClient/network_quality.h
        NeuronClient/networkvalue.cpp
        NeuronClient/networkvalue.h
        NeuronClient/NeuronClient.h
        NeuronClient/pch.cpp
        NeuronClient/pch.h
        NeuronClient/sample_cache.cpp
        NeuronClient/sample_cache.h
        NeuronClient/server.cpp
        NeuronClient/server.h
        NeuronClient/servertoclient.cpp
        NeuronClient/servertoclient.h
        NeuronClient/servertoclientletter.h
        NeuronClient/sound_filter.cpp
        NeuronClient/sound_filter.h
        NeuronClient/sound_instance.cpp
        NeuronClient/sound_instance.h
        NeuronClient/sound_library_2d.cpp
        NeuronClient/sound_library_2d.h
        NeuronClient/sound_library_2d_win32.cpp
        NeuronClient/sound_library_2d_win32.h
        NeuronClient/sound_library_3d.cpp
        NeuronClient/sound_library_3d.h
        NeuronClient/sound_library_3d_dsound.cpp
        NeuronClient/sound_library_3d_dsound.h
        NeuronClient/sound_library_3d_software.cpp
        NeuronClient/sound_library_3d_software.h
        NeuronClient/sound_library_3d_xaudio.cpp
        NeuronClient/sound_library_3d_xaudio.h
        NeuronClient/sound_parameter.cpp
        NeuronClient/sound_parameter.h
        NeuronClient/sound_stream_decoder.cpp
        NeuronClient/sound_stream_decoder.h
        NeuronClient/soundsystem.cpp
        NeuronClient/soundsystem.h
        NeuronClient/syncdiff.cpp
        NeuronClient/syncdiff.h
        NeuronClient/win32_eventhandler.cpp
        NeuronClient/win32_eventhandler.h
        NeuronClient/win32_eventproc.h
        NeuronCore/unrar/arccmt.cpp
        NeuronCore/unrar/archive.cpp
        NeuronCore/unrar/archive.h
        NeuronCore/unrar/arcread.cpp
        NeuronCore/unrar/array.h
        NeuronCore/unrar/cmddata.cpp
        NeuronCore/unrar/cmddata.h
        NeuronCore/unrar/coder.cpp
        NeuronCore/unrar/coder.h
        NeuronCore/unrar/compress.h
        NeuronCore/unrar/consio.cpp
        NeuronCore/unrar/consio.h
        NeuronCore/unrar/crc.cpp
        NeuronCore/unrar/crc.h
        NeuronCore/unrar/crypt.cpp
        NeuronCore/unrar/crypt.h
        NeuronCore/unrar/encname.cpp
        NeuronCore/unrar/encname.h
        NeuronCore/unrar/errhnd.cpp
        NeuronCore/unrar/errhnd.h
        NeuronCore/unrar/extinfo.cpp
        NeuronCore/unrar/extinfo.h
        NeuronCore/unrar/extract.cpp
        NeuronCore/unrar/extract.h
        NeuronCore/unrar/filcreat.cpp
        NeuronCore/unrar/filcreat.h
        NeuronCore/unrar/file.cpp
        NeuronCore/unrar/file.h
        NeuronCore/unrar/filefn.cpp
        NeuronCore/unrar/filefn.h
        NeuronCore/unrar/filestr.cpp
        NeuronCore/unrar/filestr.h
        NeuronCore/unrar/find.cpp
        NeuronCore/unrar/find.h
        NeuronCore/unrar/getbits.cpp
        NeuronCore/unrar/getbits.h
        NeuronCore/unrar/global.cpp
        NeuronCore/unrar/global.h
        NeuronCore/unrar/headers.h
        NeuronCore/unrar/int64.cpp
        NeuronCore/unrar/int64.h
        NeuronCore/unrar/isnt.cpp
        NeuronCore/unrar/isnt.h
        NeuronCore/unrar/list.cpp
        NeuronCore/unrar/list.h
        NeuronCore/unrar/loclang.h
        NeuronCore/unrar/log.cpp
        NeuronCore/unrar/log.h
        NeuronCore/unrar/match.cpp
        NeuronCore/unrar/match.h
        NeuronCore/unrar/memfree.h
        NeuronCore/unrar/model.cpp
        NeuronCore/unrar/model.h
        NeuronCore/unrar/options.cpp
        NeuronCore/unrar/options.h
        NeuronCore/unrar/os.h
        NeuronCore/unrar/pathfn.cpp
        NeuronCore/unrar/pathfn.h
        NeuronCore/unrar/rarbloat.cpp
        NeuronCore/unrar/rarbloat.h
        NeuronCore/unrar/rardefs.h
        NeuronCore/unrar/rarfn.h
        NeuronCore/unrar/rarlang.h
        NeuronCore/unrar/raros.h
        NeuronCore/unrar/rarresource.cpp
        NeuronCore/unrar/rarresource.h
        NeuronCore/unrar/rartypes.h
        NeuronCore/unrar/rarvm.cpp
        NeuronCore/unrar/rarvm.h
        NeuronCore/unrar/rarvmtbl.cpp
        NeuronCore/unrar/rawread.cpp
        NeuronCore/unrar/rawread.h
        NeuronCore/unrar/rdwrfn.cpp
        NeuronCore/unrar/rdwrfn.h
        NeuronCore/unrar/recvol.cpp
        NeuronCore/unrar/recvol.h
        NeuronCore/unrar/rijndael.cpp
        NeuronCore/unrar/rijndael.h
        NeuronCore/unrar/rs.cpp
        NeuronCore/unrar/rs.h
        NeuronCore/unrar/savepos.cpp
        NeuronCore/unrar/savepos.h
        NeuronCore/unrar/scantree.cpp
        NeuronCore/unrar/scantree.h
        NeuronCore/unrar/sha1.cpp
        NeuronCore/unrar/sha1.h
        NeuronCore/unrar/smallfn.cpp
        NeuronCore/unrar/smallfn.h
        NeuronCore/unrar/strfn.cpp
        NeuronCore/unrar/strfn.h
        NeuronCore/unrar/strlist.cpp
        NeuronCore/unrar/strlist.h
        NeuronCore/unrar/suballoc.cpp
        NeuronCore/unrar/suballoc.h
        NeuronCore/unrar/system.cpp
        NeuronCore/unrar/system.h
        NeuronCore/unrar/timefn.cpp
        NeuronCore/unrar/timefn.h
        NeuronCore/unrar/ulinks.cpp
        NeuronCore/unrar/ulinks.h
        NeuronCore/unrar/unicode.cpp
        NeuronCore/unrar/unicode.h
        NeuronCore/unrar/unpack.cpp
        NeuronCore/unrar/unpack.h
        NeuronCore/unrar/unpack15.cpp
        NeuronCore/unrar/unpack20.cpp
        NeuronCore/unrar/unrar.cpp
        NeuronCore/unrar/unrar.h
        NeuronCore/unrar/uowners.cpp
        NeuronCore/unrar/version.h
        NeuronCore/unrar/volume.cpp
        NeuronCore/unrar/volume.h
        NeuronCore/unrar/win32acl.cpp
        NeuronCore/unrar/win32stm.cpp
        NeuronCore/2d_array.h
        NeuronCore/2d_surface_map.h
        NeuronCore/3d_sprite.cpp
        NeuronCore/3d_sprite.h
        NeuronCore/ASyncLoader.h
        NeuronCore/auto_vector.h
        NeuronCore/binary_stream_readers.cpp
        NeuronCore/binary_stream_readers.h
        NeuronCore/bitmap.cpp
        NeuronCore/bitmap.h
        NeuronCore/bounded_array.h
        NeuronCore/btree.h
        NeuronCore/bytestream.h
        NeuronCore/darray.h
        NeuronCore/Debug.h
        NeuronCore/debug_fog_logging.cpp
        NeuronCore/debug_logging.cpp
        NeuronCore/debug_logging.h
        NeuronCore/debug_render.cpp
        NeuronCore/debug_render.h
        NeuronCore/DeviceNotify.h
        NeuronCore/directory.cpp
        NeuronCore/directory.h
        NeuronCore/Event.h
        NeuronCore/EventManager.cpp
        NeuronCore/EventManager.h
        NeuronCore/fast_darray.h
        NeuronCore/filecrc.cpp
        NeuronCore/filecrc.h
        NeuronCore/FileSys.cpp
        NeuronCore/FileSys.h
        NeuronCore/filesys_utils.cpp
        NeuronCore/filesys_utils.h
        NeuronCore/FixedPipeline.cpp
        NeuronCore/FixedPipeline.h
        NeuronCore/float_vector3.h
        NeuronCore/hash.h
        NeuronCore/hash_map_darwin.h
        NeuronCore/hash_table.h
        NeuronCore/HashData.cpp
        NeuronCore/HashData.h
        NeuronCore/hi_res_time.cpp
        NeuronCore/hi_res_time.h
        NeuronCore/invert_matrix.cpp
        NeuronCore/invert_matrix.h
        NeuronCore/language_table.cpp
        NeuronCore/language_table.h
        NeuronCore/llist.h
        NeuronCore/map_utils.h
        NeuronCore/math_utils.cpp
        NeuronCore/math_utils.h
        NeuronCore/matrix33.cpp
        NeuronCore/matrix33.h
        NeuronCore/matrix34.cpp
        NeuronCore/matrix34.h
        NeuronCore/matrix_cache.h
        NeuronCore/mouse_cursor.cpp
        NeuronCore/mouse_cursor.h
        NeuronCore/net_lib.cpp
        NeuronCore/net_lib.h
        NeuronCore/net_lib_apple.h
        NeuronCore/net_lib_win32.h
        NeuronCore/net_mutex.h
        NeuronCore/net_mutex_win32.cpp
        NeuronCore/net_socket.cpp
        NeuronCore/net_socket.h
        NeuronCore/net_socket_listener.cpp
        NeuronCore/net_socket_listener.h
        NeuronCore/net_socket_session.cpp
        NeuronCore/net_socket_session.h
        NeuronCore/net_thread.h
        NeuronCore/net_thread_win32.cpp
        NeuronCore/net_udp_packet.cpp
        NeuronCore/net_udp_packet.h
        NeuronCore/network_stream.cpp
        NeuronCore/network_stream.h
        NeuronCore/network_stream_inlines.cpp
        NeuronCore/NeuronCore.h
        NeuronCore/NeuronHelper.h
        NeuronCore/ogl_extensions.h
        NeuronCore/ogl_extensions_directx.cpp
        NeuronCore/opengl_directx.cpp
        NeuronCore/opengl_directx.h
        NeuronCore/opengl_directx_dlist.cpp
        NeuronCore/opengl_directx_dlist.h
        NeuronCore/opengl_directx_dlist_dev.cpp
        NeuronCore/opengl_directx_dlist_dev.h
        NeuronCore/opengl_directx_inline.h
        NeuronCore/opengl_directx_internals.h
        NeuronCore/opengl_directx_matrix_stack.cpp
        NeuronCore/opengl_directx_matrix_stack.h
        NeuronCore/opengl_directx_stubs.cpp
        NeuronCore/opengl_trace.cpp
        NeuronCore/opengl_trace.h
        NeuronCore/pch.cpp
        NeuronCore/pch.h
        NeuronCore/plane.cpp
        NeuronCore/plane.h
        NeuronCore/preference_names.h
        NeuronCore/preferences.cpp
        NeuronCore/preferences.h
        NeuronCore/presized_array.h
        NeuronCore/profiler.cpp
        NeuronCore/profiler.h
        NeuronCore/random_number.cpp
        NeuronCore/random_number.h
        NeuronCore/render_utils.cpp
        NeuronCore/render_utils.h
        NeuronCore/resource.cpp
        NeuronCore/resource.h
        NeuronCore/rgb_colour.cpp
        NeuronCore/rgb_colour.h
        NeuronCore/runnable.cpp
        NeuronCore/runnable.h
        NeuronCore/safegl.cpp
        NeuronCore/safegl.h
        NeuronCore/shader.cpp
        NeuronCore/shader.h
        NeuronCore/shape.cpp
        NeuronCore/shape.h
        NeuronCore/slice_darray.h
        NeuronCore/sorting_hash_table.h
        NeuronCore/sphere_renderer.cpp
        NeuronCore/sphere_renderer.h
        NeuronCore/string_utils.cpp
        NeuronCore/string_utils.h
        NeuronCore/system_info.cpp
        NeuronCore/system_info.h
        NeuronCore/targetcursor.cpp
        NeuronCore/targetcursor.h
        NeuronCore/text_file_writer.cpp
        NeuronCore/text_file_writer.h
        NeuronCore/text_renderer.cpp
        NeuronCore/text_renderer.h
        NeuronCore/text_stream_readers.cpp
        NeuronCore/text_stream_readers.h
        NeuronCore/texture.cpp
        NeuronCore/texture.h
        NeuronCore/texture_uv.cpp
        NeuronCore/texture_uv.h
        NeuronCore/tri_tri.cpp
        NeuronCore/unicode_string.cpp
        NeuronCore/unicode_string.h
        NeuronCore/unicode_text_file_writer.cpp
        NeuronCore/unicode_text_file_writer.h
        NeuronCore/unicode_text_stream_reader.cpp
        NeuronCore/unicode_text_stream_reader.h
        NeuronCore/user_info.cpp
        NeuronCore/user_info.h
        NeuronCore/vector2.cpp
        NeuronCore/vector2.h
        NeuronCore/vector3.cpp
        NeuronCore/vector3.h
        NeuronCore/window_manager.cpp
        NeuronCore/window_manager.h
        NeuronCore/window_manager_directx.cpp
        NeuronCore/window_manager_directx.h
        NeuronCore/work_queue.cpp
        NeuronCore/work_queue.h)
