#ifndef INCLUDED_UNIVERSAL_INCLUDE_H
#define INCLUDED_UNIVERSAL_INCLUDE_H

#define DARWINIA_VERSION "1.5.11"
#define DARWINIA_EXE_VERSION 1,5,11,0
#define STR_DARWINIA_EXE_VERSION "1, 5, 11, 0\0"

#define DEBUG_RENDER_ENABLED

#define DARWINIA_GAMETYPE "debug"
#define CHEATMENU_ENABLED
#define TEST_HARNESS_ENABLED
#define D3D_DEBUG_INFO
#define PROFILER_ENABLED

#define DARWINIA_VERSION_STRING DARWINIA_PLATFORM "-" DARWINIA_GAMETYPE "-" DARWINIA_VERSION

#define DARWINIA_PLATFORM "win32"

#define HAVE_DSOUND

#define SAFE_FREE(x) {free(x);x=NULL;}
#define SAFE_DELETE(x) {delete x;x=NULL;}
#define SAFE_DELETE_ARRAY(x) {delete[] x;x=NULL;}
#define SAFE_RELEASE(x) {if(x){(x)->Release();x=NULL;}}

#endif
