#ifndef _included_resource_h
#define _included_resource_h

#include "bitmap.h"
#include "shape.h"
#include "sound_stream_decoder.h"
#include "text_stream_readers.h"

class Resource
{
  protected:
    inline static unsigned int m_nameSeed = 1;

    // Bitmaps that have been registered with the resource system, so that
    // they can be used as if they had been loaded from disk or the archive.
    // USUALLY USED for AUTOGENERATED bitmaps, so that the resource system
    // can regenerate textures for them when the OpenGL context is destroyed.
    inline static std::unordered_map<std::string, BitmapRGBA*> m_bitmaps;

    inline static std::unordered_map<std::string, int> m_textures;
    inline static std::unordered_map<std::string, Shape*> m_shapes;

  public:
    // *** Initialisation/Destruction ***
    static void Startup() {}
    static void Shutdown();

    // *** Bitmaps ***
    static void AddBitmap(const char* _name, const BitmapRGBA& _bmp, bool _mipMapping = true);

    // *** Textures ***
    static int GetTexture(const char* _name, bool _mipMapping = true, bool _masked = true);
    static bool DoesTextureExist(const char* _name);

    // *** Files ***
    static TextReader* GetTextReader(std::string_view _filename);	// Caller must delete the TextReader when done
    static BinaryReader* GetBinaryReader(const char* _filename);	// Caller must delete the BinaryReader when done

    // *** Shapes ****
    // Never produces an animatable shape because the one shape is shared between all people who call this function with the same shape name. If you want an animatable shape, call GetShapeCopy
    static Shape* GetShape(const char* _name);
    static Shape* GetShapeCopy(const char* _name, bool _animating);

    // *** Normal resources ***
    static SoundStreamDecoder* GetSoundStreamDecoder(const char* _filename);	// Caller must delete the decoder when done

    static void FlushOpenGlState();
    static void RegenerateOpenGlState();

    static std::vector<std::string> ListResources(const char* _dir, const char* _filter, bool _longResults = true);
};

#endif
