/*
 * RESOURCE SYSTEM
 *
 */

#ifndef _included_resource_h
#define _included_resource_h

#include "fast_darray.h"
#include "hash_table.h"
#include "runnable.h"
#include "net_lib.h"
#include "shape.h"

class BitmapRGBA;
class TextReader;
class BinaryReader;
class SoundStreamDecoder;
class Resource;
class Runnable;

class Resource
{
  protected:
    struct TextureInfo
    {
      TextureInfo(int _id, int _width, int _height);

      int m_id;
      int m_width;
      int m_height;
    };

    NetMutex m_mutex;
    unsigned int m_nameSeed;

    // Bitmaps that have been registered with the resource system, so that
    // they can be used as if they had been loaded from disk or the archive.
    // USUALLY USED for AUTOGENERATED bitmaps, so that the resource system
    // can regenerate textures for them when the OpenGL context is destroyed.
    HashTable<BitmapRGBA*> m_bitmaps;

    HashTable<int> m_displayLists;

    using TextureHash = std::map<std::string, TextureInfo*>;
    TextureHash m_textures;

    HashTable<Shape*> m_shapes;

    char* m_modName;

    TextureInfo* ProcessBmp(BitmapRGBA& _bmp, int _flags);

  public:
    // *** Initialisation/Destruction ***
    Resource();
    ~Resource();

    // *** Bitmaps ***
    void AddBitmap(const char* _name, const BitmapRGBA& _bmp);
    const BitmapRGBA* GetBitmap(const char* _name);

    // *** Textures ***
    enum
    {
      WithMipmaps = 0x1,
      WithMask = 0x2,
      WithAlpha = 0x4,
      WithCompression = 0x8
    };

    int GetTexture(const char* _name, bool _mipMapping = true, bool _masked = true, bool _compressed = false);
    int GetTextureWithFlags(const char* _name, int _flags);
    int GetTextureWithAlpha(const char* _name);
    bool DoesTextureExist(const char* _name);
    void DeleteTexture(const char* _name);
    bool GetTextureInfo(const char* _name, int& _width, int& _height);

    // *** Files ***
    TextReader* GetTextReader(const std::string& _filename); // Caller must delete the TextReader when done
    TextReader* GetTextReader(const char* _filename); // Caller must delete the TextReader when done
    BinaryReader* GetBinaryReader(const char* _filename); // Caller must delete the BinaryReader when done

    // *** Shapes ****
    void AddShape(Shape* _shape, const char* _name);
    Shape* GetShape(const char* _name, bool _makeNew = true);
    // Never produces an animatable shape because the one shape is shared between all people who call this function with the same shape name. If you want an animatable shape, call GetShapeCopy
    Shape* GetShapeCopy(const char* _name, bool _animating, bool _buildDisplayList = true);
    bool DoesShapeExist(const char* _filename);

    // *** Normal resources ***
    SoundStreamDecoder* GetSoundStreamDecoder(const char* _filename); // Caller must delete the decoder when done

    // *** Display lists ***
    int CreateDisplayList(const char* _name); // Adds _name to the hashtable and calls glGenLists
    int CreateDisplayListAsync(const char* _name, const Runnable& _render, const Runnable& _before = NoOp(),
                               const Runnable& _after = NoOp());
    int CreateDisplayList(const char* _name, const Runnable& _render, const Runnable& _before, const Runnable& _after);

    int GetDisplayList(const char* _name); // Returns -1 if _name doesn't exist

    void DeleteDisplayList(const char* _name); // Removes _name from the hashtable and calls glDeleteLists
    void DeleteDisplayListAsync(const char* _name);
    void DeleteDisplayListAsync(int _id);

    void FlushOpenGlState();
    void RegenerateOpenGlState();

    // Returns a unique name that can be used to identify autogenerated resources. It is the caller's 
    // responsibility to delete the name later. Use "delete []" NOT "free".
    char* GenerateName();

    static std::vector<std::string> ListResources(const char* _dir, const char* _filter, bool _longResults = true);

    bool FileExists(const char* _file);
};

#endif
